### ISSUE TITLE
target/linux/ramips/dts/OMEGA2.dtsi not merged correctly

### ISSUE THREAD

**Issue by chrbayer** [WereCatf/source#1]
target/linux/ramips/dts/OMEGA2.dtsi has been merged incorrectly: uart2 and pwm sections are both present, hey should be both removed.

This is no lede problem, it happened in your repo :)

**Comment by WereCatf** [comment]
No, it's deliberate. I do not agree with the removal of PWM from the DTS and as such this is not a problem.
